"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

function nGram(n) {
  if (typeof n !== 'number' || isNaN(n) || n < 1 || n === Infinity) {
    throw new Error('`' + n + '` is not a valid argument for n-gram');
  }

  return grams;

  function grams(value) {
    var nGrams = [];
    var index;

    if (value === null || value === undefined) {
      return nGrams;
    }

    value = value.slice ? value : String(value);
    index = value.length - n + 1;

    if (index < 1) {
      return nGrams;
    }

    while (index--) {
      nGrams[index] = value.slice(index, index + n);
    }

    return nGrams;
  }
}

nGram.bigram = nGram(2);
nGram.trigram = nGram(3);
var _default = nGram;
exports.default = _default;
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.getTrigram = exports.getBigram = exports.getTokens = void 0;

var _stopwords = require("./stopwords");

var _nGram = _interopRequireDefault(require("./helpers/nGram"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _toConsumableArray(arr) { return _arrayWithoutHoles(arr) || _iterableToArray(arr) || _nonIterableSpread(); }

function _nonIterableSpread() { throw new TypeError("Invalid attempt to spread non-iterable instance"); }

function _iterableToArray(iter) { if (Symbol.iterator in Object(iter) || Object.prototype.toString.call(iter) === "[object Arguments]") return Array.from(iter); }

function _arrayWithoutHoles(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = new Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } }

var stopWordsByLangMap = {
  en: _stopwords.en,
  no: _stopwords.no
};
var defaultLang = 'en';
var splittingRegExp = new RegExp(/[&\/\\#.,!?+() $~%:*<>{}]/g);

var getTokens = function getTokens(query, lang) {
  var stopwords = lang ? stopWordsByLangMap[lang] : defaultLang;
  var queryWords = query && query.split(splittingRegExp);
  var filteredWords = queryWords && queryWords.filter(function (word) {
    return word !== '';
  });
  var wordsFormatted = filteredWords && filteredWords.map(function (word) {
    return word.toLowerCase();
  });
  var tokens = wordsFormatted.filter(function (word) {
    return !stopwords[word];
  });
  return _toConsumableArray(new Set(tokens));
};

exports.getTokens = getTokens;

var getBigram = function getBigram(tokens) {
  return _nGram.default.bigram(tokens);
};

exports.getBigram = getBigram;

var getTrigram = function getTrigram(tokens) {
  return _nGram.default.trigram(tokens);
};

exports.getTrigram = getTrigram;
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
var stopwords = {
  a: true,
  "a's": true,
  able: true,
  about: true,
  above: true,
  according: true,
  accordingly: true,
  across: true,
  actually: true,
  after: true,
  afterwards: true,
  again: true,
  against: true,
  "ain't": true,
  all: true,
  allow: true,
  allows: true,
  almost: true,
  alone: true,
  along: true,
  already: true,
  also: true,
  although: true,
  always: true,
  am: true,
  among: true,
  amongst: true,
  an: true,
  and: true,
  another: true,
  any: true,
  anybody: true,
  anyhow: true,
  anyone: true,
  anything: true,
  anyway: true,
  anyways: true,
  anywhere: true,
  apart: true,
  appear: true,
  appreciate: true,
  appropriate: true,
  are: true,
  "aren't": true,
  around: true,
  as: true,
  aside: true,
  ask: true,
  asking: true,
  associated: true,
  at: true,
  available: true,
  away: true,
  awfully: true,
  b: true,
  be: true,
  became: true,
  because: true,
  become: true,
  becomes: true,
  becoming: true,
  been: true,
  before: true,
  beforehand: true,
  behind: true,
  being: true,
  believe: true,
  below: true,
  beside: true,
  besides: true,
  best: true,
  better: true,
  between: true,
  beyond: true,
  both: true,
  brief: true,
  but: true,
  by: true,
  c: true,
  "c'mon": true,
  "c's": true,
  came: true,
  can: true,
  "can't": true,
  cannot: true,
  cant: true,
  cause: true,
  causes: true,
  certain: true,
  certainly: true,
  changes: true,
  clearly: true,
  co: true,
  com: true,
  come: true,
  comes: true,
  concerning: true,
  consequently: true,
  consider: true,
  considering: true,
  contain: true,
  containing: true,
  contains: true,
  corresponding: true,
  could: true,
  "couldn't": true,
  course: true,
  currently: true,
  d: true,
  definitely: true,
  described: true,
  despite: true,
  did: true,
  "didn't": true,
  different: true,
  do: true,
  does: true,
  "doesn't": true,
  doing: true,
  "don't": true,
  done: true,
  down: true,
  downwards: true,
  during: true,
  e: true,
  each: true,
  edu: true,
  eg: true,
  eight: true,
  either: true,
  else: true,
  elsewhere: true,
  enough: true,
  entirely: true,
  especially: true,
  et: true,
  etc: true,
  even: true,
  ever: true,
  every: true,
  everybody: true,
  everyone: true,
  everything: true,
  everywhere: true,
  ex: true,
  exactly: true,
  example: true,
  except: true,
  f: true,
  far: true,
  few: true,
  fifth: true,
  first: true,
  five: true,
  followed: true,
  following: true,
  follows: true,
  for: true,
  former: true,
  formerly: true,
  forth: true,
  four: true,
  from: true,
  further: true,
  furthermore: true,
  g: true,
  get: true,
  gets: true,
  getting: true,
  given: true,
  gives: true,
  go: true,
  goes: true,
  going: true,
  gone: true,
  got: true,
  gotten: true,
  greetings: true,
  h: true,
  had: true,
  "hadn't": true,
  happens: true,
  hardly: true,
  has: true,
  "hasn't": true,
  have: true,
  "haven't": true,
  having: true,
  he: true,
  "he's": true,
  hello: true,
  help: true,
  hence: true,
  her: true,
  here: true,
  "here's": true,
  hereafter: true,
  hereby: true,
  herein: true,
  hereupon: true,
  hers: true,
  herself: true,
  hi: true,
  him: true,
  himself: true,
  his: true,
  hither: true,
  hopefully: true,
  how: true,
  howbeit: true,
  however: true,
  i: true,
  "i'd": true,
  "i'll": true,
  "i'm": true,
  "i've": true,
  ie: true,
  if: true,
  ignored: true,
  immediate: true,
  in: true,
  inasmuch: true,
  inc: true,
  indeed: true,
  indicate: true,
  indicated: true,
  indicates: true,
  inner: true,
  insofar: true,
  instead: true,
  into: true,
  inward: true,
  is: true,
  "isn't": true,
  it: true,
  "it'd": true,
  "it'll": true,
  "it's": true,
  its: true,
  itself: true,
  j: true,
  just: true,
  k: true,
  keep: true,
  keeps: true,
  kept: true,
  know: true,
  knows: true,
  known: true,
  l: true,
  last: true,
  lately: true,
  later: true,
  latter: true,
  latterly: true,
  least: true,
  less: true,
  lest: true,
  let: true,
  "let's": true,
  like: true,
  liked: true,
  likely: true,
  little: true,
  look: true,
  looking: true,
  looks: true,
  ltd: true,
  m: true,
  mainly: true,
  many: true,
  may: true,
  maybe: true,
  me: true,
  mean: true,
  meanwhile: true,
  merely: true,
  might: true,
  more: true,
  moreover: true,
  most: true,
  mostly: true,
  much: true,
  must: true,
  my: true,
  myself: true,
  n: true,
  name: true,
  namely: true,
  nd: true,
  near: true,
  nearly: true,
  necessary: true,
  need: true,
  needs: true,
  neither: true,
  never: true,
  nevertheless: true,
  new: true,
  next: true,
  nine: true,
  no: true,
  nobody: true,
  non: true,
  none: true,
  noone: true,
  nor: true,
  normally: true,
  not: true,
  nothing: true,
  novel: true,
  now: true,
  nowhere: true,
  o: true,
  obviously: true,
  of: true,
  off: true,
  often: true,
  oh: true,
  ok: true,
  okay: true,
  old: true,
  on: true,
  once: true,
  one: true,
  ones: true,
  only: true,
  onto: true,
  or: true,
  other: true,
  others: true,
  otherwise: true,
  ought: true,
  our: true,
  ours: true,
  ourselves: true,
  out: true,
  outside: true,
  over: true,
  overall: true,
  own: true,
  p: true,
  particular: true,
  particularly: true,
  per: true,
  perhaps: true,
  placed: true,
  please: true,
  plus: true,
  possible: true,
  presumably: true,
  probably: true,
  provides: true,
  q: true,
  que: true,
  quite: true,
  qv: true,
  r: true,
  rather: true,
  rd: true,
  re: true,
  really: true,
  reasonably: true,
  regarding: true,
  regardless: true,
  regards: true,
  relatively: true,
  respectively: true,
  right: true,
  s: true,
  said: true,
  same: true,
  saw: true,
  say: true,
  saying: true,
  says: true,
  second: true,
  secondly: true,
  see: true,
  seeing: true,
  seem: true,
  seemed: true,
  seeming: true,
  seems: true,
  seen: true,
  self: true,
  selves: true,
  sensible: true,
  sent: true,
  serious: true,
  seriously: true,
  seven: true,
  several: true,
  shall: true,
  she: true,
  should: true,
  "shouldn't": true,
  since: true,
  six: true,
  so: true,
  some: true,
  somebody: true,
  somehow: true,
  someone: true,
  something: true,
  sometime: true,
  sometimes: true,
  somewhat: true,
  somewhere: true,
  soon: true,
  sorry: true,
  specified: true,
  specify: true,
  specifying: true,
  still: true,
  sub: true,
  such: true,
  sup: true,
  sure: true,
  t: true,
  "t's": true,
  take: true,
  taken: true,
  tell: true,
  tends: true,
  th: true,
  than: true,
  thank: true,
  thanks: true,
  thanx: true,
  that: true,
  "that's": true,
  thats: true,
  the: true,
  their: true,
  theirs: true,
  them: true,
  themselves: true,
  then: true,
  thence: true,
  there: true,
  "there's": true,
  thereafter: true,
  thereby: true,
  therefore: true,
  therein: true,
  theres: true,
  thereupon: true,
  these: true,
  they: true,
  "they'd": true,
  "they'll": true,
  "they're": true,
  "they've": true,
  think: true,
  third: true,
  this: true,
  thorough: true,
  thoroughly: true,
  those: true,
  though: true,
  three: true,
  through: true,
  throughout: true,
  thru: true,
  thus: true,
  to: true,
  together: true,
  too: true,
  took: true,
  toward: true,
  towards: true,
  tried: true,
  tries: true,
  truly: true,
  try: true,
  trying: true,
  twice: true,
  two: true,
  u: true,
  un: true,
  under: true,
  unfortunately: true,
  unless: true,
  unlikely: true,
  until: true,
  unto: true,
  up: true,
  upon: true,
  us: true,
  use: true,
  used: true,
  useful: true,
  uses: true,
  using: true,
  usually: true,
  uucp: true,
  v: true,
  value: true,
  various: true,
  very: true,
  via: true,
  viz: true,
  vs: true,
  w: true,
  want: true,
  wants: true,
  was: true,
  "wasn't": true,
  way: true,
  we: true,
  "we'd": true,
  "we'll": true,
  "we're": true,
  "we've": true,
  welcome: true,
  well: true,
  went: true,
  were: true,
  "weren't": true,
  what: true,
  "what's": true,
  whatever: true,
  when: true,
  whence: true,
  whenever: true,
  where: true,
  "where's": true,
  whereafter: true,
  whereas: true,
  whereby: true,
  wherein: true,
  whereupon: true,
  wherever: true,
  whether: true,
  which: true,
  while: true,
  whither: true,
  who: true,
  "who's": true,
  whoever: true,
  whole: true,
  whom: true,
  whose: true,
  why: true,
  will: true,
  willing: true,
  wish: true,
  with: true,
  within: true,
  without: true,
  "won't": true,
  wonder: true,
  would: true,
  "wouldn't": true,
  x: true,
  y: true,
  yes: true,
  yet: true,
  you: true,
  "you'd": true,
  "you'll": true,
  "you're": true,
  "you've": true,
  your: true,
  yours: true,
  yourself: true,
  yourselves: true,
  z: true,
  zero: true
};
var _default = stopwords;
exports.default = _default;
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "en", {
  enumerable: true,
  get: function get() {
    return _en.default;
  }
});
Object.defineProperty(exports, "no", {
  enumerable: true,
  get: function get() {
    return _no.default;
  }
});

var _en = _interopRequireDefault(require("./en"));

var _no = _interopRequireDefault(require("./no"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
var stopwords = {
  en: true,
  "a's": true,
  'i stand': true,
  om: true,
  ovenfor: true,
  'i følge': true,
  følgelig: true,
  'på tvers': true,
  faktisk: true,
  etter: true,
  etterpå: true,
  igjen: true,
  imot: true,
  'er ikke': true,
  alt: true,
  tillate: true,
  tillater: true,
  nesten: true,
  alene: true,
  sammen: true,
  allerede: true,
  også: true,
  'selv om': true,
  alltid: true,
  er: true,
  blant: true,
  og: true,
  'en annen': true,
  noe: true,
  'hvem som helst': true,
  uansett: true,
  'hva som helst': true,
  allikevel: true,
  'hvor som helst': true,
  'fra hverandre': true,
  vises: true,
  'setter pris på': true,
  passende: true,
  rundt: true,
  som: true,
  'til side': true,
  spør: true,
  assosiert: true,
  på: true,
  tilgjengelig: true,
  borte: true,
  forferdelig: true,
  b: true,
  'vær ærlig': true,
  ble: true,
  fordi: true,
  bli: true,
  blir: true,
  vært: true,
  før: true,
  'på forhånd': true,
  bak: true,
  'å være': true,
  tro: true,
  nedenfor: true,
  'ved siden av': true,
  dessuten: true,
  best: true,
  bedre: true,
  mellom: true,
  utover: true,
  'begge deler': true,
  kort: true,
  men: true,
  av: true,
  c: true,
  "c'mon": true,
  "c's": true,
  'gikk i oppfyllelse': true,
  kan: true,
  'kan ikke': true,
  årsak: true,
  årsaker: true,
  sikkert: true,
  absolutt: true,
  endringer: true,
  tydelig: true,
  co: true,
  com: true,
  angående: true,
  vurdere: true,
  vurderer: true,
  inneholder: true,
  'som inneholder': true,
  tilsvarende: true,
  kunne: true,
  'kunne ikke': true,
  kurs: true,
  'for tiden': true,
  d: true,
  definitivt: true,
  beskrevet: true,
  'til tross for': true,
  gjorde: true,
  'gjorde ikke': true,
  annerledes: true,
  gjør: true,
  ikke: true,
  gjort: true,
  ned: true,
  nedover: true,
  under: true,
  e: true,
  hver: true,
  edu: true,
  'f.eks': true,
  åtte: true,
  enten: true,
  annet: true,
  'andre steder': true,
  nok: true,
  helt: true,
  spesielt: true,
  et: true,
  osv: true,
  'til og med': true,
  noensinne: true,
  'alle sammen': true,
  alle: true,
  overalt: true,
  eks: true,
  nøyaktig: true,
  eksempel: true,
  unntatt: true,
  f: true,
  langt: true,
  få: true,
  femte: true,
  først: true,
  fem: true,
  fulgte: true,
  følgende: true,
  følger: true,
  for: true,
  tidligere: true,
  frem: true,
  fire: true,
  fra: true,
  videre: true,
  g: true,
  får: true,
  gitt: true,
  gir: true,
  gå: true,
  går: true,
  fikk: true,
  fått: true,
  hilsener: true,
  h: true,
  hadde: true,
  'hadde ikke': true,
  skjer: true,
  neppe: true,
  har: true,
  'har ikke': true,
  'å ha': true,
  han: true,
  hei: true,
  hjelp: true,
  derav: true,
  henne: true,
  her: true,
  'her er': true,
  heretter: true,
  herved: true,
  hennes: true,
  'seg selv': true,
  ham: true,
  hans: true,
  hit: true,
  forhåpentligvis: true,
  hvor: true,
  howbeit: true,
  imidlertid: true,
  jeg: true,
  'jeg ville': true,
  'jeg vil': true,
  'jeg er': true,
  'jeg har': true,
  dvs: true,
  hvis: true,
  ignorert: true,
  øyeblikkelig: true,
  i: true,
  'for så vidt': true,
  inc: true,
  indikerer: true,
  indikert: true,
  indre: true,
  'i stedet': true,
  'inn i': true,
  innover: true,
  'det er': true,
  'det ville': true,
  'det vil': true,
  j: true,
  bare: true,
  k: true,
  holde: true,
  holder: true,
  beholdt: true,
  vet: true,
  kjent: true,
  l: true,
  sist: true,
  'i det siste': true,
  senere: true,
  sistnevnte: true,
  minst: true,
  mindre: true,
  'for ikke': true,
  la: true,
  'la oss': true,
  likte: true,
  sannsynlig: true,
  lite: true,
  se: true,
  'ser ut': true,
  ltd: true,
  m: true,
  hovedsakelig: true,
  mange: true,
  kanskje: true,
  meg: true,
  betyr: true,
  'i mellomtiden': true,
  mer: true,
  mest: true,
  mye: true,
  må: true,
  min: true,
  'meg selv': true,
  n: true,
  navn: true,
  nemlig: true,
  nd: true,
  'i nærheten av': true,
  nødvendig: true,
  trenger: true,
  behov: true,
  'heller ikke': true,
  aldri: true,
  likevel: true,
  nytt: true,
  neste: true,
  ni: true,
  nei: true,
  ingen: true,
  noone: true,
  normalt: true,
  ingenting: true,
  roman: true,
  nå: true,
  ingensteds: true,
  o: true,
  åpenbart: true,
  ofte: true,
  å: true,
  ok: true,
  OK: true,
  gammel: true,
  'en gang': true,
  ett: true
};
var _default = stopwords;
exports.default = _default;
