const stopwords = {
  en: true,
  "a's": true,
  'i stand': true,
  om: true,
  ovenfor: true,
  'i følge': true,
  følgelig: true,
  'på tvers': true,
  faktisk: true,
  etter: true,
  etterpå: true,
  igjen: true,
  imot: true,
  'er ikke': true,
  alt: true,
  tillate: true,
  tillater: true,
  nesten: true,
  alene: true,
  sammen: true,
  allerede: true,
  også: true,
  'selv om': true,
  alltid: true,
  er: true,
  blant: true,
  og: true,
  'en annen': true,
  noe: true,
  'hvem som helst': true,
  uansett: true,
  'hva som helst': true,
  allikevel: true,
  'hvor som helst': true,
  'fra hverandre': true,
  vises: true,
  'setter pris på': true,
  passende: true,
  rundt: true,
  som: true,
  'til side': true,
  spør: true,
  assosiert: true,
  på: true,
  tilgjengelig: true,
  borte: true,
  forferdelig: true,
  b: true,
  'vær ærlig': true,
  ble: true,
  fordi: true,
  bli: true,
  blir: true,
  vært: true,
  før: true,
  'på forhånd': true,
  bak: true,
  'å være': true,
  tro: true,
  nedenfor: true,
  'ved siden av': true,
  dessuten: true,
  best: true,
  bedre: true,
  mellom: true,
  utover: true,
  'begge deler': true,
  kort: true,
  men: true,
  av: true,
  c: true,
  "c'mon": true,
  "c's": true,
  'gikk i oppfyllelse': true,
  kan: true,
  'kan ikke': true,
  årsak: true,
  årsaker: true,
  sikkert: true,
  absolutt: true,
  endringer: true,
  tydelig: true,
  co: true,
  com: true,
  angående: true,
  vurdere: true,
  vurderer: true,
  inneholder: true,
  'som inneholder': true,
  tilsvarende: true,
  kunne: true,
  'kunne ikke': true,
  kurs: true,
  'for tiden': true,
  d: true,
  definitivt: true,
  beskrevet: true,
  'til tross for': true,
  gjorde: true,
  'gjorde ikke': true,
  annerledes: true,
  gjør: true,
  ikke: true,
  gjort: true,
  ned: true,
  nedover: true,
  under: true,
  e: true,
  hver: true,
  edu: true,
  'f.eks': true,
  åtte: true,
  enten: true,
  annet: true,
  'andre steder': true,
  nok: true,
  helt: true,
  spesielt: true,
  et: true,
  osv: true,
  'til og med': true,
  noensinne: true,
  'alle sammen': true,
  alle: true,
  overalt: true,
  eks: true,
  nøyaktig: true,
  eksempel: true,
  unntatt: true,
  f: true,
  langt: true,
  få: true,
  femte: true,
  først: true,
  fem: true,
  fulgte: true,
  følgende: true,
  følger: true,
  for: true,
  tidligere: true,
  frem: true,
  fire: true,
  fra: true,
  videre: true,
  g: true,
  får: true,
  gitt: true,
  gir: true,
  gå: true,
  går: true,
  fikk: true,
  fått: true,
  hilsener: true,
  h: true,
  hadde: true,
  'hadde ikke': true,
  skjer: true,
  neppe: true,
  har: true,
  'har ikke': true,
  'å ha': true,
  han: true,
  hei: true,
  hjelp: true,
  derav: true,
  henne: true,
  her: true,
  'her er': true,
  heretter: true,
  herved: true,
  hennes: true,
  'seg selv': true,
  ham: true,
  hans: true,
  hit: true,
  forhåpentligvis: true,
  hvor: true,
  howbeit: true,
  imidlertid: true,
  jeg: true,
  'jeg ville': true,
  'jeg vil': true,
  'jeg er': true,
  'jeg har': true,
  dvs: true,
  hvis: true,
  ignorert: true,
  øyeblikkelig: true,
  i: true,
  'for så vidt': true,
  inc: true,
  indikerer: true,
  indikert: true,
  indre: true,
  'i stedet': true,
  'inn i': true,
  innover: true,
  'det er': true,
  'det ville': true,
  'det vil': true,
  j: true,
  bare: true,
  k: true,
  holde: true,
  holder: true,
  beholdt: true,
  vet: true,
  kjent: true,
  l: true,
  sist: true,
  'i det siste': true,
  senere: true,
  sistnevnte: true,
  minst: true,
  mindre: true,
  'for ikke': true,
  la: true,
  'la oss': true,
  likte: true,
  sannsynlig: true,
  lite: true,
  se: true,
  'ser ut': true,
  ltd: true,
  m: true,
  hovedsakelig: true,
  mange: true,
  kanskje: true,
  meg: true,
  betyr: true,
  'i mellomtiden': true,
  mer: true,
  mest: true,
  mye: true,
  må: true,
  min: true,
  'meg selv': true,
  n: true,
  navn: true,
  nemlig: true,
  nd: true,
  'i nærheten av': true,
  nødvendig: true,
  trenger: true,
  behov: true,
  'heller ikke': true,
  aldri: true,
  likevel: true,
  nytt: true,
  neste: true,
  ni: true,
  nei: true,
  ingen: true,
  noone: true,
  normalt: true,
  ingenting: true,
  roman: true,
  nå: true,
  ingensteds: true,
  o: true,
  åpenbart: true,
  ofte: true,
  å: true,
  ok: true,
  OK: true,
  gammel: true,
  'en gang': true,
  ett: true
}

export default stopwords
